# Generated by Django 5.0.6 on 2025-05-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('instid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsPaleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('instid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion')),
            ],
            options={
                'unique_together': {('instid', 'color')},
            },
        ),
    ]
