# Generated by Django 5.0.6 on 2025-05-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
