# Generated by Django 5.0.6 on 2025-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_alter_institucion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='¿Ha sido validada/aprobada por un administrador?'),
        ),
    ]
