# Generated by Django 5.0.6 on 2025-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajeroviaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', help_text='Estado de la aceptación del pasajero para el viaje', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasajeroviaje',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasajeroviaje',
            name='puntuacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
