# Generated by Django 5.0.6 on 2025-05-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('celular', models.IntegerField()),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('instid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioType',
            fields=[
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('uid', 'tipo', 'url')},
            },
        ),
    ]
