# Generated by Django 5.0.6 on 2025-05-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_documento_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
