# Generated by Django 5.0.6 on 2025-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_documento_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='¿Ha sido aprobado por la institución?'),
        ),
    ]
