# Generated by Django 5.0.6 on 2025-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='¿Vehículo aprobado por la institución?'),
        ),
    ]
